name: esp32_control
description: Cross-platform BLE controller for an ESP32.
publish_to: none
version: 1.2.0+3

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: 2.3.12
  shared_preferences: 2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
